pipeline {
    agent any
    stages {
		stage('NewFeature'){
            steps{
                echo 'Starting aging job'
                build job: 'PIPELINE-FULL-NEWFEATURE', parameters: [
                      string(name:'ENVIRONMENT', value: "newfeature")]
            }
        }
        stage('Merge NewFeature-Develop'){
            steps{
                sh script: """
                    set -x
                    git branch -a
                    git checkout -b newfeature-one origin/newfeature-one
                    git checkout -b develop origin/develop
                    git merge develop
                """, label: "Merging code to develop"
                sshagent(['github']) {
                       withCredentials([gitUsernamePassword(credentialsId: 'github',
                       gitToolName: 'git-tool')]) {
                               sh 'git push origin develop'
                               }                
                }
            }
        }        
        stage('Staging'){
            steps{
                echo 'Starting aging job'
                build job: 'PIPELINE-FULL-STAGING', parameters: [
                      string(name:'ENVIRONMENT', value: "staging")]
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}
