pipeline {
    agent any
    stages {
        
        stage('Staging'){
            steps{
                echo 'Starting the staging job'
                build job: 'PIPELINE-FULL-STAGING', parameters: [
                      string(name:'ENVIRONMENT', value: "staging")]
            }
        }
        stage('Merge'){
            withCredentials([git credentialsId: 'b0770b7e-2b4d-4ab9-8b6a-e2002fb60da0', url: 'https://github.com/ivngmz/todo-list-aws.git']){
            steps{
                sh script: '''
                    set -x
                    cd /home/ubuntu/environment/todo-list-aws/
                    git branch -a
                    git checkout -b develop origin/develop
                    git checkout -b master origin/master
                    git merge develop
                ''', label: "Merging code to master"
                sshagent(['github']) {
                    sh "git push origin master"
                }
              }
            }
        }
        stage('Production'){
            steps{
                
                echo 'Starting production job'
                build job: 'PIPELINE-FULL-PRODUCTION', parameters: [
                      string(name:'ENVIRONMENT', value: "production")]
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}
